
FROM ubuntu:20.04

RUN yum -y install python3 && \
    yum -y install unzip && \
    curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" && \
    unzip awscliv2.zip && \
    ./aws/install

COPY python_script.py /usr/src/app/
WORKDIR /usr/src/app
CMD ["python3", " /usr/src/app/python_script.py"]